### PR TITLE
Fix ANRs during Position Checks

### LINKED ISSUE #8: MUX Stat Config is freezing player's UI
Hi, we are having some issues on several users since Sep 16th

Bitmovin Version: 3.23.0 (we tested with these 3 version, 3.11.1 and 3.18.1, no problems were found, we published the app 2 days before the issue appeared)
MUX SDK Version: 0.5.1

What is happening: Mux configuration is freezing the player UI, content audio can be listened, after a while Android alert pop up.

Here is the Stat Configuration:

```
val player = Player.create(this, playerConfig = playerConfig).also {
                bView.bitmovinPlayerView.player = it
            }
            //setup player listeners
            setupPlayerListeners()
            //Load playlist
            player.load(playlistConfig)
            setMUXConfig()
```

```
private fun setMUXConfig() {
        Log.e("here", "MUX Config")

        try {
            val customerPlayerData = CustomerPlayerData()
            customerPlayerData.environmentKey = BuildConfig.MUX_KEY
            val customerVideoData = CustomerVideoData()
            customerVideoData.videoTitle = titleVideo
            customerVideoData.videoId = titleVideoID
            customerVideoData.videoSeries = episodeName
            customerPlayerData.playerInitTime = getCurrentNowMilliseconds()
            customerPlayerData.subPropertyId = BuildConfig.SUB_PROPERTY_ID
            val customerData = CustomerData(customerPlayerData, customerVideoData, null)

            muxStatsBitmovin = MuxStatsSDKBitmovinPlayer(
                this,
                bView.bitmovinPlayerView,
                "Riivi",
                customerData)

            val size = Point()
            windowManager.defaultDisplay.getSize(size)
            muxStatsBitmovin?.setScreenSize(size.x, size.y)

        } catch (e: Exception){
            Log.e("mux", "${e.message}")
        }

    }
```

And here is the Stacktrace:

```
  at com.mux.stats.sdk.muxstats.MuxStats.handle (unavailable:2)
  at com.mux.stats.sdk.core.events.EventBus.dispatch (unavailable:24)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.dispatch (MuxStatsSDKBitmovinPlayer.java:587)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.buffering (MuxStatsSDKBitmovinPlayer.java:386)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.lambda$new$10$com-mux-stats-sdk-muxstats-bitmovinplayer-MuxStatsSDKBitmovinPlayer (MuxStatsSDKBitmovinPlayer.java:263)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer$$ExternalSyntheticLambda11.onEvent (unavailable:4)
  at com.bitmovin.player.api.event.EventEmitter$DefaultImpls$d.a (SourceFile:1)
  at com.bitmovin.player.api.event.EventEmitter$DefaultImpls$d.invoke (SourceFile:1)
  at com.bitmovin.player.u.b.b (SourceFile:206)
  at com.bitmovin.player.u.d.a (SourceFile:1)
  at com.bitmovin.player.f.p0.a (SourceFile:42)
  at com.bitmovin.player.f.p0.a (SourceFile:1)
  at com.bitmovin.player.f.p0.b (SourceFile:1)
  at com.bitmovin.player.f.p0$a.a (SourceFile:2)
  at com.bitmovin.player.f.p0$a.invoke (SourceFile:1)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit (Emitters.kt:223)
  at kotlinx.coroutines.flow.StateFlowImpl.collect (StateFlow.kt:398)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect (SafeCollector.common.kt:113)
  at kotlinx.coroutines.flow.FlowKt__CollectKt.collect (Collect.kt:30)
  at kotlinx.coroutines.flow.FlowKt.collect (unavailable:1)
  at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.invokeSuspend (Collect.kt:50)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8663)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```

### PR DESCRIPTION
**Pull request by daytime-em**
Apparently bitmovin's `duration` field is not always stable to call depending on the state of the player. We should prefer to observe bitmovin's state totally asynchronously.

This fixes #8

### CODE REVIEW

File: muxstatssdkbitmovinplayer/src/main/java/com/mux/stats/sdk/muxstats/bitmovinplayer/MuxStatsSDKBitmovinPlayer.java [hunk 1]
```diff
@@ -519,12 +519,12 @@ public Float getSourceAdvertisedFramerate() {
...
     @Override
     public Long getSourceDuration() {
-        return secondsToMs(player.get().getPlayer().getDuration());
+        return secondsToMs(playbackPosition);
     }
 
     @Override
     public boolean isPaused() {
-        return player.get().getPlayer().isPaused();
+        return state == PlayerState.PAUSED;
```
Comment (nbirkenshaw-mux) [inline muxstatssdkbitmovinplayer/src/main/java/com/mux/stats/sdk/muxstats/bitmovinplayer/MuxStatsSDKBitmovinPlayer.java:527]: Are we sure that this change is safe?

For example, when paused while seeking would the previous implementation have returned true or false? (From what I can tell the new one would return false).

**Review by nbirkenshaw-mux — APPROVED** [review]
